/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SignOutRouteImport } from './routes/sign-out'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthJacketsIndexRouteImport } from './routes/_auth/jackets/index'
import { Route as AuthJacketsJacketIdRouteImport } from './routes/_auth/jackets/$jacketId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SignOutRoute = SignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthJacketsIndexRoute = AuthJacketsIndexRouteImport.update({
  id: '/jackets/',
  path: '/jackets/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthJacketsJacketIdRoute = AuthJacketsJacketIdRouteImport.update({
  id: '/jackets/$jacketId',
  path: '/jackets/$jacketId',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/sign-out': typeof SignOutRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/jackets/$jacketId': typeof AuthJacketsJacketIdRoute
  '/jackets/': typeof AuthJacketsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/sign-out': typeof SignOutRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/': typeof AuthIndexRoute
  '/jackets/$jacketId': typeof AuthJacketsJacketIdRoute
  '/jackets': typeof AuthJacketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/sign-out': typeof SignOutRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/jackets/$jacketId': typeof AuthJacketsJacketIdRoute
  '/_auth/jackets/': typeof AuthJacketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/not-found'
    | '/sign-out'
    | '/unauthorized'
    | '/jackets/$jacketId'
    | '/jackets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/not-found'
    | '/sign-out'
    | '/unauthorized'
    | '/'
    | '/jackets/$jacketId'
    | '/jackets'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/not-found'
    | '/sign-out'
    | '/unauthorized'
    | '/_auth/'
    | '/_auth/jackets/$jacketId'
    | '/_auth/jackets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotFoundRoute: typeof NotFoundRoute
  SignOutRoute: typeof SignOutRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-out': {
      id: '/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof SignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/jackets/': {
      id: '/_auth/jackets/'
      path: '/jackets'
      fullPath: '/jackets/'
      preLoaderRoute: typeof AuthJacketsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/jackets/$jacketId': {
      id: '/_auth/jackets/$jacketId'
      path: '/jackets/$jacketId'
      fullPath: '/jackets/$jacketId'
      preLoaderRoute: typeof AuthJacketsJacketIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthJacketsJacketIdRoute: typeof AuthJacketsJacketIdRoute
  AuthJacketsIndexRoute: typeof AuthJacketsIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthJacketsJacketIdRoute: AuthJacketsJacketIdRoute,
  AuthJacketsIndexRoute: AuthJacketsIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  NotFoundRoute: NotFoundRoute,
  SignOutRoute: SignOutRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
